projects:
  graphqlreactscn:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 55npw6ivmbanncau3ievjliwui
      endpoints:
        prod: >-
          https://qd4lhqyplbaf7dyvrkpngg4ft4.appsync-api.us-east-1.amazonaws.com/graphql
